name: slo-report

on:
  workflow_run:
    workflows: ['slo']
    types:
      - completed

jobs:
  test-ydb-slo-action:
    runs-on: ubuntu-latest
    name: Publish YDB SLO Report
    permissions:
      contents: read
      pull-requests: write
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Publish YDB SLO Report
        uses: ydb-platform/ydb-slo-action/report@charts
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
